feat: implement rsa signer / verifier
web3-storage/ucanto pull request #102
Opened 2022-09-30 07:52 UTC by Gozala

2022-10-12 16:27 UTC, Gozala commented on packages/principal/src/ed25519/type.ts
> +  encode: () => ByteView<EdVerifier<M>>
```suggestion
  encode: () => ByteView<EdVerifier<M>>
  export: () => ByteView<EdVerifier<M>>
```

2022-10-12 17:24 UTC, hugomrdias requested changes

2022-10-12 17:24 UTC, hugomrdias commented on packages/interface/src/lib.ts
> +  toCryptoKey?: () => Await<CryptoKey>
```suggestion
  exportBytes?: () => Await<ByteView<Signer<M, A>>>
  exportKey?: () => Await<CryptoKey>
```

2022-10-12 17:24 UTC, hugomrdias commented on packages/interface/src/lib.ts
> +  toCryptoKey?: () => Await<CryptoKey>
```suggestion
  exportBytes?: () => Await<ByteView<Verifier<M, A>>>
  exportKey?: () => Await<CryptoKey>
```

2022-10-12 17:24 UTC, hugomrdias commented on packages/principal/test/ed25519.spec.js
> +    const derived = await Lib.derive(original.secret)
ed has a derive method ? we need to have a smaller api surface please and consistency in the names what ever they are

2022-10-13 07:49 UTC, Gozala commented
@hugomrdias I have trimmed interface per your feedback. Now `Verifier` is simply a `UCAN.Verifier` and `Signer` only extends `UCAN.Signer` with a single `toArchive` method which returns either bytes (if underlying key is extractable) or `{did, key}` pair which can be saved into IndexedDB and later restored via `Signer.from(archive)`. This should remove any need for try catch / or if guarding.

I hope these changes address your concerns, please have another pass and let me know whether to proceed or if there are some other concerns to be addressed.

2022-10-13 16:52 UTC, hugomrdias approved these changes
LGTM

2022-10-13 16:52 UTC, hugomrdias commented on packages/interface/src/lib.ts
> +   *   const archive = signer.toAchive()
```suggestion
   *   const archive = signer.toArchive()
```

2022-10-13 16:52 UTC, hugomrdias commented on packages/interface/src/lib.ts
> +   *   } else (signer.exportKey) {
```suggestion
   *   } else {
```

2022-10-13 16:52 UTC, hugomrdias commented on packages/principal/src/rsa.js
> +    this.privateKey
```suggestion
```

2022-10-13 16:52 UTC, hugomrdias commented on packages/principal/src/rsa/private-key.js
> +const base6urlDecode = (input = '') => base64url.baseDecode(input)
```suggestion
const base64urlDecode = (input = '') => base64url.baseDecode(input)
```

2022-10-13 17:13 UTC, merged