W3 signer token
web3-storage/ucanto pull request #62
Opened 2022-06-25 22:52 UTC by ice-breaker-tg

Extends options for the signer service and the SIGV4 to allow passing the security token generated when a temp IAM is used instead of a user based one.

2022-06-29 06:04 UTC, Gozala commented
@hugomrdias I don't know why this is still failing, it should be fixed by #67 and it is on my device. I suspect there is some caching happening and new changes in target branch aren't picked up on reruns.

2022-06-29 06:08 UTC, Gozala commented
@ice-breaker-tg do you mind doing `git fetch && git merge origin/main && git push` which I believe should fix the failing test. Since pr is from your fork, I'm unable to add any commits here.

2022-06-29 19:38 UTC, ice-breaker-tg commented
> @ice-breaker-tg do you mind doing `git fetch && git merge origin/main && git push` which I believe should fix the failing test. Since pr is from your fork, I'm unable to add any commits here.

Did this, ran tests locally and they all passed so hopefully should be good.
Let me know if there is anything else.

2022-06-30 11:13 UTC, hugomrdias requested changes
Can you please change the param name to `sessionToken` to keep it the same as the s3 sdk ?

2022-06-30 11:13 UTC, hugomrdias commented on w3/sigv4/src/index.js
> +      params.set('x-amz-security-token', this.securityToken)
```suggestion
      params.set('X-Amz-Security-Token', this.securityToken)
```

2022-07-11 11:35 UTC, hugomrdias approved these changes

2022-07-11 11:35 UTC, merged